SELECT MEMBER_NAME,REVIEW_TEXT, date_format(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE
INNER JOIN (
    SELECT REST_REVIEW .* FROM REST_REVIEW 
    INNER JOIN (
            SELECT MEMBER_ID, COUNT(*) AS CNT 
            FROM  REST_REVIEW 
            GROUP BY MEMBER_ID
            ORDER BY CNT DESC
            LIMIT 1
        )T1
    ON REST_REVIEW.MEMBER_ID = T1.MEMBER_ID
)T2
ON MEMBER_PROFILE.MEMBER_ID = T2.MEMBER_ID
ORDER BY REVIEW_DATE,REVIEW_TEXT