SELECT SUM(g.SCORE) AS SCORE, emp.EMP_NO, emp.EMP_NAME, emp.POSITION, emp.EMAIL
FROM HR_EMPLOYEES emp
JOIN HR_GRADE g
ON emp.EMP_NO = g.EMP_NO
WHERE g.YEAR = 2022
GROUP BY emp.EMP_NO, emp.EMP_NAME, emp.POSITION, emp.EMAIL
ORDER BY SCORE DESC
LIMIT 1;